# Generated by `crucible create {job_name} --kind job`. Feel free to edit.

import logging
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
	# Supports direct execution: python jobs/{job_name}/job.py
	sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from crucible.core.jobs import AbstractJob


logger = logging.getLogger(__name__)


class Job(AbstractJob):
	"""Scaffolded job '{job_name}'."""

	def on_prepare(self) -> None:
		self.data = {{"status": "ready"}}

	def on_execute(self) -> dict[str, str]:
		logger.info("Job '{job_name}' executed with data status: %s", self.data["status"])
		return {{"status": "ok", "job": "{job_name}", "kind": "job"}}


JOB_CLASS = Job
