# Generated by `crucible create {run_name} --job-type standalone`. Feel free to edit.
from __future__ import annotations

import logging
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
	# Supports direct execution: python runs/{run_name}/runner.py
	sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from crucible.core.jobs import AbstractJob


logger = logging.getLogger(__name__)


class Job(AbstractJob):
	"""Scaffolded standalone job for run '{run_name}'."""

	def setup_data(self) -> None:
		self.data = {{"status": "ready"}}

	def run(self) -> dict[str, str]:
		self.setup()
		logger.info("Run '{run_name}' executed with data status: %s", self.data["status"])
		return {{"status": "ok", "task": "{run_name}", "mode": "standalone"}}


JOB_CLASS = Job
