# Generated by `crucible create {run_name} --job-type training`. Feel free to edit.
from __future__ import annotations

import logging
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
	# Supports direct execution: python runs/{run_name}/runner.py
	sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from crucible.core.jobs import AbstractTrainerJob


logger = logging.getLogger(__name__)


class Job(AbstractTrainerJob):
	"""Scaffolded training job for run '{run_name}'."""

	def setup_data(self) -> None:
		self.data = {{"status": "ready"}}

	def setup_model(self) -> None:
		self.model = {{"name": "dummy-model"}}

	def setup_metrics(self) -> None:
		self.metrics = {{}}

	def train(self) -> dict[str, str]:
		logger.info("Training run '{run_name}' started with model: %s", self.model["name"])
		return {{"status": "ok", "task": "{run_name}", "mode": "training"}}

	def evaluate(self) -> dict[str, str]:
		return {{"status": "ok"}}


JOB_CLASS = Job
