# Generated by `crucible create simple_mlp_on_mnist --kind job`. Feel free to edit.

import logging
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
	# Supports direct execution: python jobs/simple_mlp_on_mnist/job.py
	sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from crucible.core.jobs import AbstractJob


logger = logging.getLogger(__name__)


class Job(AbstractJob):
	"""Scaffolded job 'simple_mlp_on_mnist'."""

	def on_prepare(self) -> None:
		self.data = {"status": "ready"}

	def on_execute(self) -> dict[str, str]:
		logger.info("Job 'simple_mlp_on_mnist' executed with data status: %s", self.data["status"])
		return {"status": "ok", "job": "simple_mlp_on_mnist", "kind": "job"}


JOB_CLASS = Job
